routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return redirect()->to('index');
});
Route::get('lessonIndex', 'MainController@lessonIndex');
Route::get('aboutIndex', 'MainController@aboutIndex');
Route::get('blogIndex', 'MainController@blogIndex');
Route::get('contactIndex', 'MainController@contactIndex');
Route::get('errorIndex', 'MainController@errorIndex');
Route::get('blogPostMore', 'MainController@blogPostMore');
Route::get('lessonBooking', 'MainController@lessonBooking');

Route::resource('index', 'MainController');
Route::resource('session', 'SessionController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('user')->middleware('user');

Route::get('/admin', 'AdminController@adminRole')->name('admin')->middleware('admin');
Route::get('adminProfile', 'AdminController@adminProfile');
Route::resource('adminc', 'AdminController');

// Route::get('/user', 'UserController@index')->name('user')->middleware('user');
Route::get('/teacher', 'TeacherController@index')->name('teacher')->middleware('teacher');

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'lastName', 'gender', 'birthDay', 'phone', 'school', 'class', 'registerNumber', 'cerficateNumber', 'introduction', 'fatherName', 'fatherPhone', 'motherName', 'motherPhone', 'addresss', 'status_id', 'role', 'softDelete',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

class UserController extends Controller
{
    public function index()
    {
        return view('users.index');
    }
}

resources/views/user/about.blade.php
@extends('../userLayout.master')

@section('aboutIndex')
<!-- sfmaskldgnjksldjfkasdjgkashjgsdfkslfsaljfsla -->
<!--about-us-->
<section class="section pt-50">
    <div class="container-fluid">
        <div class="row ">
            <div class="col-lg-8 mt-30">
                <div class="about-us">
                    <div class="about-us-image">
                        <img src="assets/img/about-us.jpg" alt="">
                    </div>
                    <div class="description">
                        <h6> Бидний Танилцуулгыг Сонирхож Байгаад Баярлалаа </h6>
                        <p>Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга
                            Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга
                            Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга
                            Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга
                            Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга
                            Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга
                            Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга
                        </p>
                        <p>
                            Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга
                            Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга
                            Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга
                            Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга
                            Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга
                            Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга
                            Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга
                        </p>
                        <div class="quote">
                            <div>
                                <i class="icon_quotations_alt"></i>
                            </div>
                            <p>
                                "Урам Үг Урам Үг Урам Үг Урам Үг Урам Үг Урам Үг Урам Үг Урам Үг Урам Үг Урам Үг
                                Урам Үг Урам Үг Урам Үг ”
                            </p>
                            <small> Захирал </small>
                        </div>
                        <p>
                            Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга
                            Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга
                            Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга
                            Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга
                            Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга
                            Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга
                            Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга Танилцуулга
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 max-width">
                <div class="widget">
                    <div class="section-title">
                        <h5> Зураг </h5>
                    </div>
                    <ul class="widget-instagram">
                        <li>
                            <a class="image" href="#">
                                <img src="assets/img/instagram/1.jpg" alt="">
                            </a>
                        </li>
                        <li>
                            <a class="image" href="#">
                                <img src="assets/img/instagram/2.jpg" alt="">
                            </a>
                        </li>
                        <li>
                            <a class="image" href="#">
                                <img src="assets/img/instagram/3.jpg" alt="">
                            </a>
                        </li>
                        <li>
                            <a class="image" href="#">
                                <img src="assets/img/instagram/4.jpg" alt="">
                            </a>
                        </li>
                        <li>
                            <a class="image" href="#">
                                <img src="assets/img/instagram/5.jpg" alt="">
                            </a>
                        </li>
                        <li>
                            <a class="image" href="#">
                                <img src="assets/img/instagram/6.jpg" alt="">
                            </a>
                        </li>
                        <li>
                            <a class="image" href="#">
                                <img src="assets/img/instagram/7.jpg" alt="">
                            </a>
                        </li>
                        <li>
                            <a class="image" href="#">
                                <img src="assets/img/instagram/8.jpg" alt="">
                            </a>
                        </li>
                        <li>
                            <a class="image" href="#">
                                <img src="assets/img/instagram/9.jpg" alt="">
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>


@endsection

resources/views/user/blog.blade.php
@extends('../userLayout.master')

@section('blogIndex')

<!--category-->
<section class="categorie-section">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 alert alert-info">
                <div class="categorie-title">
                    <p>
                        <strong>
                            Энэхүү мэдээллийн хэсэг нь тухайн сайт дээр явагдаж байгаа хичээлийн талаар болон сурах
                            явцыг хөнгөвчлөх нэмэлт мэдээлэл оруулах зорилготой юм.
                        </strong>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<!--blog-grid-->
<section class="blog-grid">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 mt-30">
                <div class="row">

                    <div class="col-lg-4 col-md-4">
                        <!--Post-1-->
                        <div class="post-card">
                            <div class="post-card-image">
                                <a href="post-default.html">
                                    <img src="assets/img/blog/1.jpg" alt="">
                                </a>
                            </div>
                            <div class="post-card-content">
                                <a href="blog-grid.html" class="categorie">Монгол Хэл</a>
                                <h5>
                                    <a href="postView.html"> Монгол Бичгийг Хэрхэн Хялбар Цээжлэх Вэ </a>
                                </h5>
                                <p> Цээжлэх Цээжлэх Цээжлэх Цээжлэх Цээжлэх Цээжлэх Цээжлэх Цээжлэх Цээжлэх Цээжлэх
                                    Цээжлэх Цээжлэх Цээжлэх </p>
                                <div class="post-card-info">
                                    <ul class="list-inline">
                                        <li>
                                            <a href="author.html">
                                                <img src="assets/img/author/1.jpg" alt="">
                                            </a>
                                        </li>
                                        <li>
                                            <a href="author.html"> Содгэрэл </a>
                                        </li>
                                        <li class="dot"></li>
                                        <li> Нийтэлсэн Огноо </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!--/-->
                    </div>
                    <div class="col-lg-4 col-md-4">
                        <!--Post-1-->
                        <div class="post-card">
                            <div class="post-card-image">
                                <a href="post-default.html">
                                    <img src="assets/img/blog/1.jpg" alt="">
                                </a>
                            </div>
                            <div class="post-card-content">
                                <a href="blog-grid.html" class="categorie">Монгол Хэл</a>
                                <h5>
                                    <a href="post-default.html"> Монгол Бичгийг Хэрхэн Хялбар Цээжлэх Вэ </a>
                                </h5>
                                <p> Цээжлэх Цээжлэх Цээжлэх Цээжлэх Цээжлэх Цээжлэх Цээжлэх Цээжлэх Цээжлэх Цээжлэх
                                    Цээжлэх Цээжлэх Цээжлэх </p>
                                <div class="post-card-info">
                                    <ul class="list-inline">
                                        <li>
                                            <a href="author.html">
                                                <img src="assets/img/author/1.jpg" alt="">
                                            </a>
                                        </li>
                                        <li>
                                            <a href="author.html"> Содгэрэл </a>
                                        </li>
                                        <li class="dot"></li>
                                        <li> Нийтэлсэн Огноо </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!--/-->
                    </div>
                    <div class="col-lg-4 col-md-4">
                        <!--Post-1-->
                        <div class="post-card">
                            <div class="post-card-image">
                                <a href="post-default.html">
                                    <img src="assets/img/blog/1.jpg" alt="">
                                </a>
                            </div>
                            <div class="post-card-content">
                                <a href="blog-grid.html" class="categorie">Монгол Хэл</a>
                                <h5>
                                    <a href="post-default.html"> Монгол Бичгийг Хэрхэн Хялбар Цээжлэх Вэ </a>
                                </h5>
                                <p> Цээжлэх Цээжлэх Цээжлэх Цээжлэх Цээжлэх Цээжлэх Цээжлэх Цээжлэх Цээжлэх Цээжлэх
                                    Цээжлэх Цээжлэх Цээжлэх </p>
                                <div class="post-card-info">
                                    <ul class="list-inline">
                                        <li>
                                            <a href="author.html">
                                                <img src="assets/img/author/1.jpg" alt="">
                                            </a>
                                        </li>
                                        <li>
                                            <a href="author.html"> Содгэрэл </a>
                                        </li>
                                        <li class="dot"></li>
                                        <li> Нийтэлсэн Огноо </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!--/-->
                    </div>




                    <!--pagination-->
                    <div class="col-lg-12">
                        <div class="pagination mt--10">
                            <ul class="list-inline">
                                <li class="active">
                                    <a href="#">1</a>
                                </li>
                                <li>
                                    <a href="#">2</a>
                                </li>
                                <li>
                                    <a href="#">3</a>
                                </li>
                                <li>
                                    <a href="#">4</a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="arrow_carrot-2right"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--/-->


@endsection

resources/views/user/error.blade.php
@extends('../userLayout.master')

@section('errorIndex')

<section class="section pt-55 mb-50">
    <div class="container-fluid">
        <div class="page404  widget">
            <div class="image">
                <img src="assets/img/404.jpg" alt="">
            </div>
            <div class="content">
                <h1>404</h1>
                <h3> Ийм Хуудас Олдсонгүй </h3>
                <a href="index.html" class="btn-custom"> Нүүр Хуудасруу Буцах </a>
            </div>
        </div>
    </div>
</section>

@endsection

resources/views/user/lesson.blade.php
@extends('../userLayout.master')


@section('lessonIndex')
<!--post-default-->
<section class="section pt-55">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-4 max-width">
                <!-- Lesson Check -->
                <div class="widget">
                    <div class="widget-author">
                        <h6>
                            <span> Хичээл Сонголт </span>
                        </h6>
                    </div>
                    @php
                    $i=1;
                    @endphp
                    @if(isset($subClaName))
                    @if(count($subClaName)>0)
                    @foreach($subClaName as $key => $value)
                    <div class="form-check">
                        <label class="form-check-label" for="">

                            <a class="link" style="margin: 5px; font-size:medium;"
                                href="{{route('index.create', ['lessonId'=> $value->subClaId])}}">
                                {{$i++}}) {{$value->subClaName}}
                            </a>
                        </label>
                    </div>


                    @endforeach
                    @endif
                    @endif
                </div>
                <!-- Class Check -->
                <div class=" widget">
                    <div class="widget-author">
                        <h6>
                            <span> Анги Сонголт </span>
                        </h6>
                    </div>
                    @if(isset($classNumber))
                    @if(count($classNumber)>0)
                    @foreach($classNumber as $key=> $sNumber)
                    <div class="form-check">
                        <label class="form-check-label" for="">

                            <a class="link" style="margin: 5px; font-size:medium;"
                                href="{{route('index.create', ['sNumber'=> $sNumber->subClassId])}}">
                                {{$sNumber->subClassNumber}} - р анги
                            </a>
                        </label>
                    </div>
                    @endforeach
                    @endif
                    @endif

                </div>
                <!--/-->
                <!-- <div class="widget">
                    <div class="widget-author">
                        <h6>
                            <span> Үнийн Дүн Заах </span>
                        </h6>
                    </div>
                    <strong class="range-slider__value">

                        <p> Үнийн Дүн: </p>
                    </strong>
                    <div class="range-slider__slider">
                        <input type="range" min="1000" max="30000" step="1000" value="1000" class="range"
                            id="rangeSlider" />
                    </div>
                </div> -->
            </div>

            @section('lessonSearchComponent')
            <div class="col-lg-8 mb-20">
                @if(isset($teacherSelectionLesson))
                @if(count($teacherSelectionLesson)>0)
                @foreach($teacherSelectionLesson as $key => $teaLesson)
                <div class="widget mb-50 filter_data">
                    <ul class="widget-comments">
                        <li class="comment-item">
                            <img src="{{asset('assets/img/author/1.jpg')}}" alt="">
                            <div class="content">
                                <ul class="info list-inline">
                                    <li> {{$teaLesson->name}} </li>
                                    <li class="dot"></li>
                                    <li> Элссэн Он </li>
                                    <li class="dot"></li>
                                    <li> Ажиллсан Жил </li>
                                </ul>
                                <p> {{$teaLesson->teaSelIntro}}
                                </p>
                                <div>
                                    <a class="link">
                                        </i> {{$teaLesson->subClaName}} </a>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
                @endforeach

                @else
                <section class="section pt-55 mb-50">
                    <div class="container-fluid">
                        <div class="page404  widget">
                            <div class="image">
                                <img src="assets/img/404.jpg" alt="">
                            </div>
                            <div class="content">
                                <h1>404</h1>
                                <h3> Илэрц Байхгүй Байна </h3>
                            </div>
                        </div>
                    </div>
                </section>
                @endif
                @endif
                <div class="col-lg-12">
                    <div class="pagination mt--10">
                        <ul class="list-inline">
                            <li class="active"><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">4</a></li>
                            <li><a href="#"><i class="arrow_carrot-2right"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>





@endsection



<!-- <script type="text/javascript">
$(document).ready(function() {
    console.log("test");

    $(function filter_data() {
        var action = "{{route('index.create')}}";
        var subName = get_filter('subName');
        var subNumber = get_filter('subNumber');
        console.log(subName);

        $.ajax({
            url: "{{route('index.create')}}",
            method: "get",
            data: {
                action: action,
                subName: subName,
                subNumber: subNumber
            },
            success: function(data) {
                $('.filter_data').html(data);
                console.log(filter_data);
            }
        });
    });

    function get_filter() {
        var filter = [];
        $('.' + subName + ':checked').each(function() {
            filter.push($(this).val());
            console.log("test");
        });
        return filter;
    }
});
</script> -->
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->

@endsection

resources/views/user/lessonBooking.blade.php
@extends('../userLayout.master')

@section('lessonBooking')

<section class="section author full-space mb-40 pt-55">
    <div class="container-fluid">
        <div class="row">
            @if(isset($teacherView))
            @if(count($teacherView)>0)
            @foreach($teacherView as $key=> $teacherView)
            <div class="col-lg-12">
                <!--widget-author-->
                <div class="widget-author ">
                    <a href="author.html" class="image">
                        <img src="assets/img/author/1.jpg" alt="">
                    </a>
                    <h6><span> {{$teacherView->name}}</span></h6>
                    <div class="link"> {{$teacherView->subClaName}}
                        {{$teacherView->subClassNumber}} </div>

                    <p> {{$teacherView->introduction}}
                    </p>

                    <div class="social-media">
                        <ul class="list-inline">
                            <li>
                                <a href="#" class="color-facebook">
                                    <i class="fab fa-facebook"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="color-instagram">
                                    <i class="fab fa-instagram"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="color-youtube">
                                    <i class="fab fa-youtube"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div style="margin-top: 20px;" class="col-lg-12">
                <div class="widget-author">
                    {{$teacherView->teaSelIntro}}
                </div>
            </div>
            @endforeach
            @endif
            @endif
        </div>
    </div>
</section>

<!--mansory-layout-->
<section class="masonry-layout col2-layout mt-30">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                @if(session()->has('message'))
                <div style="text-align: center;" class="alert alert-success">
                    {{ session()->get('message') }}
                </div>
                @endif
                <form action="{{route('session.store')}}" enctype="multipart/form-data" method="post">
                    @csrf
                    @if(isset($teacherTime))
                    @if(count($teacherTime)>0)
                    @foreach($teacherTime as $key=> $teacherTime)
                    <div style="background-color:burlywood; float: left; margin:10px; padding:5px;">
                        <input class="@error('teaTime') is-invalid @enderror" type="checkbox" name="sStartTime" id=""
                            value="{{$teacherTime->teaTimeSelTime}}">
                        <label for="">{{$teacherTime->teaTimeSelTime}} </label>
                        @error('sStartTime')
                        <div class="alert alert-danger">
                            {{$message}}
                        </div>
                        @enderror
                    </div>
                    @endforeach
                    @endif
                    @endif
                    <input type="hidden" name="sTeaSelSubClassId" value="{{$teacherView->subClassId}}">
                    <input type="hidden" name="sTeaSelSubClaId" value="{{$teacherView->subClaId}}">
                    <input type="hidden" name="sStudentId" value="{{auth()->user()->id}}">
                    <input type="hidden" name="sTeacherSelectId" value="{{$teacherView->id}}">
                    <?php date_default_timezone_set("Asia/Ulaanbaatar");?>
                    <input type="hidden" name="sBookingDate"
                        value="<?php echo date_default_timezone_get() . " " . date("Y/m/d/H:i:s") ?>" id="">

                    <input type="date" name="sStartDate" value="<?php echo date("Y-m-d") ?>"
                        min="<?php echo date("Y-m-d") ?>">
                    <button type="submit"> Захиалах </button>
                </form>
            </div>
        </div>
    </div>
</section>


@endsection